#!/usr/bin/env bash

INTERFACE="$1"
EVENT="$2"

if [[ "$EVENT" == "up" || "$EVENT" == "dhcp6-change" ]]; then
	/etc/serverscripts/simple-ddns.sh --config_dir=/etc/serverscripts/simple-ddns.config/ --host YOUR_HOST --trigger NetworkManager_dispatcher_$EVENT
else
  echo "$(date) [NetworkManager]: IGNORING EVENT ${EVENT} " >> $LOG_FILE
fi

